name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    labels: 'feature'
  - title: '🐛 Fixes'
    labels: 'fix'
  - title: '🛠 Maintenance'
    labels: 'chore'
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
no-changes-template: '- No changes'
