name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true  # Include submodules

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    - name: Install Composer dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Install git-archive-all
      run: pip install git-archive-all

    - name: Build Plugin
      run: make release

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Checkout code (to get correct commit hash)
      uses: actions/checkout@v3

    - name: Draft Release Notes
      id: draft_release
      uses: release-drafter/release-drafter@v5
      with:
        config-name: release-drafter.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref_name == 'refs/heads/main' && 'rolling-release' || github.ref_name }}
        release_name: ${{ github.ref_name == 'refs/heads/main' && 'Rolling Release' || github.ref_name }}
        body: ${{ steps.draft_release.outputs.changelog }}
        draft: false
        prerelease: ${{ github.ref == 'refs/heads/main' }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/*.zip
        asset_name: $(PLUGIN_NAME)-$(VERSION).zip
        asset_content_type: application/zip
