name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'   # Matches v1.0.0, v1.0.1-beta, etc.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true  # Include submodules

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    - name: Install Composer dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Install git-archive-all
      run: pip install git-archive-all

    - name: Build Plugin
      run: make release

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: portal-builder
        path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')

    steps:

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name == 'main' && 'rolling-release' || github.ref_name }}
        release_name: ${{ github.ref_name == 'main' && 'Rolling Release' || github.ref_name }}
        draft: false
        prerelease: ${{ github.ref_name == 'main' || startsWith(github.ref, 'refs/tags/') }}

    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/*.zip
        asset_name: $(basename dist/*.zip)
        asset_content_type: application/zip


  changelog:
    needs: release
    runs-on: ubuntu-latest
    steps:
    - name: Release Drafter
      uses: release-drafter/release-drafter@v5
      with:
        config-name: release-drafter.yml
